### ISSUE TITLE
HTTPS and change admin port

### ISSUE THREAD

**Issue by selfyguy** [weerdbg/weer-support#2]
1. Is there a way to change the admin port from the default 9527?

2. Does it support HTTPS/SSL?

Thanks.

**Comment by muzuiget** [comment]
> 1. Is there a way to change the admin port from the default 9527?

You can use `-l`  argument， eg: `-l 0.0.0.0:9000`

> 2. Does it support HTTPS/SSL?

Current release is not support, I still working on it.
