### ISSUE TITLE
界面上所有图标无法显示

### ISSUE THREAD

**Issue by zealotrunner** [weerdbg/weer-support#4]
点击功能正常
![20210702181032](https://user-images.githubusercontent.com/534380/124259217-da417b80-db60-11eb-902f-5d11db52c311.jpg)

**Comment by muzuiget** [comment]
竟然还有人用。

我测试了下，还是可以的，下个最新版 v0.2.3。

**Comment by image72** [comment]
@muzuiget 
最新版本 直接就启动不了. 最新版本0.23
![image](https://user-images.githubusercontent.com/243154/127450983-af529e4f-9c4c-4a46-8330-805db5fd173c.png)

**Comment by muzuiget** [comment]
估计是哪个依赖库不兼容 macOS 11.4 的样子。

**Comment by muzuiget** [comment]
你确定没下载错版本吧？用 `file` 命令看一下执行文件类型。

**Comment by image72** [comment]
没有下载错版本
![image](https://user-images.githubusercontent.com/243154/127590044-e0c07909-cbf8-4d72-aef5-9ea40acc0eb4.png)

**Comment by image72** [comment]
OS: Darwin arm64 20.5.0/Apple M1

**Comment by muzuiget** [comment]
晕，x86 的程序当然不能直接跑在 arm 上，要专门编译。你只能用 Rosetta 2 这个工具来运行。

**Comment by image72** [comment]
我就是做开发的
电脑已经安装Rosetta 2， 你可以找一台m1电脑测试下看

**Comment by muzuiget** [comment]
所以问题是我没有 M1 电脑。

**Comment by image72** [comment]
github actions 支持m1 osx build

**Comment by image72** [comment]
[.github/workflows/m1_ci.yml](https://github.com/hexops/mach/commit/b00cfe051509545cdc3f07099bd23a43c09952bf)

**Comment by image72** [comment]
https://circleci.com/blog/self-hosted-runners-add-arm-support-to-circleci/

**Comment by zealotrunner** [comment]
> 竟然还有人用。
> 
> 我测试了下，还是可以的，下个最新版 v0.2.3。

你好，之前没列清楚。
Mac 10.15.7
weer 0.2.3
Chrome 96.0.4664.93

但图标不出的问题在我这已经好久了，可能有一年了。
从很早的版本我就开始用了。
一开始是正常的，后来某个时间开始后就没再恢复。weer 和 Chrome 都升级过很多次。


另外，weer 很好用，很适合我的场景。很感谢。

我是把它用作 mitmproxy 的 web 端使用（借助 PCAP 管道）。
因为 mitmproxy 的自带 web 不够好用。

**Comment by muzuiget** [comment]
现在还有这个问题？

**Comment by zealotrunner** [comment]
我看最新有 0.2.4，还没升级。升级后再看看。
（ changelog 页面没写更新项目……）

**Comment by muzuiget** [comment]
因为只是纯粹把所有依赖库和编译工具升级到最新版本，然后重新编译一次而已。

如果看不到图片，你可以按 F12 弹出开发者工具，看看是否图片地址获取失败，404 之类的。

**Comment by zealotrunner** [comment]
是否是这个情况？

![20211214145642](https://user-images.githubusercontent.com/534380/145948394-15b7803a-01db-4210-9b68-b79cbea29101.jpg)

**Comment by muzuiget** [comment]
![Screenshot_20211214_150305](https://user-images.githubusercontent.com/330812/145949100-2f5be737-2d74-4aae-b19f-bc736c4cb0aa.png)

我是这样的。

**Comment by zealotrunner** [comment]
我猜是 Mac 和 Windows 的 Chrome  他俩图片资源不一致？

**Comment by muzuiget** [comment]
![Screenshot_20211214_150539](https://user-images.githubusercontent.com/330812/145949391-1c3d1208-256b-42fb-bb92-4df3f1587264.png)

重现到了，应该使用的是 4K 屏幕把，所以请求了双倍清晰度的图片，我没有打包进去。

**Comment by zealotrunner** [comment]
有点不像，我这的 Images 目录里，连非2x的 LargeIcons.png 也没有，/devtools/ 目录结构和你大不一样

**Comment by muzuiget** [comment]
试下用 Chrome 内建的前端连接：

```
devtools://devtools/bundled/inspector.html?ws=127.0.0.1:9527
```

把 `ws=127.0.0.1:9527` 换成你的监听地址。

**Comment by muzuiget** [comment]
你应该看 Network 那里是不是有 404，Sources 那里是请求成功的。

**Comment by zealotrunner** [comment]
> 试下用 Chrome 内建的前端连接：
> 
> ```
> devtools://devtools/bundled/inspector.html?ws=127.0.0.1:9527
> ```
> 
> 把 `ws=127.0.0.1:9527` 换成你的监听地址。

我这里看，Network 里面没有出现任何来自 weer 界面的资源请求，更没有 404 等情况。（并不是因为开了 filter）

不过这个界面倒是可以替代 weer 界面来用……

![20211214152549](https://user-images.githubusercontent.com/534380/145952133-089824e7-4097-40cd-a23b-372355074174.jpg)

**Comment by muzuiget** [comment]
本来就可以，weer 启动那个监听端口是 http/websocket 协议两用的，以 http 协议访问就返回 weer 内部的前端页面，魔改精简过的。

**Comment by muzuiget** [comment]
其实是任何 [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) 客户端都行，比如用 VS Code 也可以。

**Comment by muzuiget** [comment]
此项目已废弃，归档此仓库。
